// serivce data is scraped from
// https://www.ozbargain.com.au/user/83105/edit/referrals
export const services = [
  '3commas',
  'abra',
  'accor plus',
  'active truth',
  'admirals',
  'adore beauty',
  'aeg power tools',
  'afterpay',
  'ahm health insurance',
  'airalo',
  'airbike',
  'airbnb - airbnb host',
  'airtax',
  'airvpn',
  'airwallex',
  'aliexpress',
  'alpha-h',
  'alternative brewing',
  'amaysim',
  'amber',
  'amber electric',
  'american express - essential credit card',
  'american express - platinum business card',
  'american express - platinum card',
  'american express - platinum edge credit card',
  'american express - qantas discovery card',
  'american express - qantas ultimate card',
  'american express - qantas premium card',
  'american express - velocity platinum card',
  'american express - velocity escape card',
  'american express - david jones platinum card',
  'american express - explorer credit card',
  'american express - qantas business rewards card',
  'american express - gold credit card',
  'american express - business explorer card',
  'amino z',
  'ampol',
  'appliances online',
  'appsumo',
  'artscow - 1. new accounts',
  'artscow - mousepad',
  'artscow - tank top',
  'artscow - cosmetic bag',
  'artscow - photo specialbook',
  'artscow - watch',
  'artscow - leggings',
  'artscow - 10 selected items',
  'artscow - skater skirt',
  'artscow - phone case',
  'artscow - name stamp',
  'asos',
  'athena home loan',
  'athletic greens',
  'aussie broadband',
  'aussie house sitters',
  'aussie pharma direct',
  'awardwallet',
  'backblaze',
  'bamboo',
  'banggood',
  'bano',
  'baopals',
  'barbell foods',
  'beach burrito',
  'beam',
  'beam wallet',
  'beeco',
  'beerco',
  'beerhug',
  'befrugal',
  'belong - belong (mobile)',
  'belong - belong broadband',
  "ben & jerry's inside scoop",
  'better world books',
  'bicycle nsw',
  'bill hero',
  'billy bubbles',
  'binance - standard',
  'binance - lite - usdt',
  'binary lane',
  'bird',
  'bitpanda',
  'bitstamp',
  'black type x',
  'block earner',
  'blossom',
  'bluetti australia',
  'blys',
  'board game master',
  'bokksu',
  'bondi sands',
  'boody bamboo clothing',
  'boost your super',
  'border bank',
  'bose australia',
  'boxcryptor - boxcryptor unlimited',
  'brand house direct',
  'brazilian beauty',
  'brookfarm',
  'brooks running',
  'bubble tea club',
  'bulk nutrients',
  'bulk powders',
  'bunny.net',
  'bupa',
  'butterfly network',
  'buyandship',
  'bybit',
  'byte australia',
  'cake defi',
  'caltex / star mart - caltex fuelpay',
  'canningvale',
  'canva',
  'carbar',
  'cardly',
  'cariuma',
  'cashrewards',
  'castlery',
  'cat harness australia',
  'cell care',
  'cellar one',
  'cellardoor.co',
  'chargie',
  "chargrill charlie's",
  'chatbooks',
  'chatime',
  'cheeky plant co.',
  'chefgood',
  'chefs on wheels',
  'chief nutrition',
  'chipolo',
  'chope - chope phuket',
  'circles.life',
  'classpass',
  'cmc markets',
  'code camp',
  'coinbase',
  'coinjar',
  'coinlist',
  'coinspot',
  'coinstash',
  'cointracker',
  'cointracking',
  'cointree crypto exchange',
  'comgateway',
  'comptia',
  'coolkidz australia',
  'core powerfoods',
  'covau energy',
  'cowcow - name stamp',
  'cowcow - custom handbag mirrors',
  'cowcow - custom glasses cloths',
  'cowcow - $0.99 shoptell items',
  'cowcow - $3.99 shoptell items',
  'cowcow - $7.99 shoptell items',
  'creative labs',
  'crypto.com',
  'cryptospend',
  'cubo ai',
  'cult beauty',
  'cupshe',
  'currencyfair',
  "daniel's donuts",
  'dash delivers',
  'dashlane',
  'datacamp',
  'dataquest',
  'decathlon australia',
  'degoo',
  'dharma bums',
  'diamond energy',
  'didi - didi',
  'digital ocean',
  'dinner twist',
  'dinnerly',
  'distrokid',
  "doctors' health fund",
  'dollar shave club - fbuy.me links',
  'doordash',
  'doordash - drivers/dashers only',
  'douugh',
  'driva',
  'drop',
  'dropbox',
  'duolingo',
  'dynadot',
  'dynalist',
  'e-living furniture',
  'e-pocket',
  'easyequities',
  'eatclub',
  'eco. modern essentials',
  'econaps',
  'educative',
  'elbaite',
  'elite supplements',
  'ellus & krue',
  'emma sleep',
  'energy locals',
  'enphase',
  'eskimo',
  'etax accountants',
  'ethique',
  'etoro',
  'ettitude',
  'eubi australia',
  'euca (proud products)',
  'eva mattress',
  'evee',
  'evernote',
  'everyplate',
  'evolve skateboards',
  'exetel',
  'expressvpn',
  'eyebuydirect',
  'ezlicence',
  'fanatical',
  'fancraze',
  'fantastic services',
  'fantuan',
  'fastcover',
  'fastmail',
  'felix mobile',
  'fever',
  'fig & blooms',
  'filefactory',
  'first table australia',
  'fishme',
  'fite',
  'fitness first',
  'fitstop',
  'fiverr',
  'flexicar',
  'flexiroam',
  'flip tv',
  'floraly',
  'foody bag',
  'found concrete',
  'framefox',
  'freelancer',
  'freeletics',
  'french sweet',
  'from japan',
  'funding',
  'furthr',
  'future broadband',
  'future golf',
  'fuzenet internet',
  'gameology',
  'gami chicken & beer',
  'garden of vegan',
  'gate.io',
  'gdgt deals (engadget stacksocial)',
  'gelid store',
  'gemini exchange',
  'giffgaff',
  'gimme',
  'giving assistant',
  'glamcorner',
  'globird energy',
  'gocashback',
  'gocatch',
  'goldfields toys & games',
  'good pair days',
  'goodments',
  'goodnessme',
  'google workspace',
  'gozney',
  'groupon uk',
  'guzman y gomez',
  'gwent',
  'gym and fitness',
  'hay',
  'hello drinks',
  'hellofresh - $70 off 1st box',
  'hellofresh - $50 off 1st box ("free box")',
  'her black book',
  'heritage bank - $250 gift card with loan',
  'hey bianca',
  'hif',
  'hillview farms',
  'hipcamp',
  'hnry',
  'hodlnaut',
  'homeseer',
  'honey',
  'honey insurance',
  'hopper',
  'hotel tonight',
  'hp instant ink',
  'hqhair',
  'humble bundle - humble choice',
  'hummingbird',
  'hyper karting',
  'icebreaker',
  'ifttt',
  'ig group',
  'iherb.com',
  'independent reserve',
  'infinicloud',
  'ingogo',
  'instantscripts',
  'instarem',
  'institchu',
  'integrately',
  'interactive brokers australia',
  'ipantry',
  'iri shopper panel',
  'italki',
  'ivacy vpn',
  'iwoot',
  'jamie kay',
  'jimmy brings',
  'joonya eco wipes',
  'juniper',
  'just wines',
  "kennards self storage - kennard's self storage",
  'ker-ching!',
  'keychron',
  'kickback australia',
  "kiehl's",
  'kitsch',
  'kiwico',
  'klarna',
  'klook travel',
  'knobby',
  'knockaround',
  'koala',
  'kobo',
  'kogan',
  'koh',
  'koinly',
  'koogle',
  'krisp',
  'kucoin',
  'launtel',
  'leaptel',
  'ledger',
  'ledn',
  'life cykel',
  'lila beauty',
  'lime',
  'lingoda',
  'linode',
  'loaded lifting',
  'loans.com.au',
  'localcart',
  'lookfantastic au',
  'lookfantastic uk',
  "looma's",
  'loop',
  'loyalty app',
  'lskd',
  'lucy & yak',
  'lumin',
  'lumo energy',
  'luno',
  'luxury escapes',
  'macro mike',
  'macros',
  'mad paws',
  'marley spoon',
  'marriott',
  'mashable',
  'mate communicate',
  'max brenner',
  'me bank',
  'mealpal',
  'medibank private',
  'mee audio',
  'memberbuy',
  'menulog - drivers/couriers',
  'mexc global',
  'mingle seasoning',
  'minisforum',
  'missguided australia',
  'mixbook',
  'mobvoi',
  'modibodi',
  'mojo power',
  'momentum energy',
  'moneygram',
  'monta',
  'moo',
  'moogoo',
  'moomoo',
  'morpher',
  'mr. rebates',
  'mubi',
  'muscle nation',
  'my foodie box',
  'mypaynow',
  'myprotein',
  'myus.com',
  'naked wines',
  'nanoblock',
  'naritas finance',
  'native deodorant',
  'natural cycles',
  'natvia',
  'navexa',
  'nba top shot',
  'nectr',
  'neowin',
  'neuron mobility',
  'news demon',
  'nexo',
  'nielsen - homescan',
  'nightowl convenience',
  'noa home',
  'nodeone',
  'nomador',
  'nonda',
  'nordvpn',
  'normcore coffee',
  'nourished life',
  'novelship',
  'numobile',
  'nuraphone',
  'nutrition xpress',
  'oakley',
  'oculus',
  'okcoin',
  'okx',
  'olive young',
  'one.com - warp',
  'onedrive',
  'onmarket bookbuilds',
  'orange poland',
  'orbitkey',
  'orbitremit',
  'origin energy - origin spike',
  'origin energy - origin',
  'ororo',
  'otaku mode',
  'oura',
  'outschool',
  'ovo energy',
  'oz hair & beauty',
  'ozsale',
  'ozsale mobile',
  'panda remit',
  'parabo press',
  'park on king',
  'parkhound',
  'patpat',
  'patricks',
  'pay.com.au',
  'payo',
  'paysend',
  'pd car insurance',
  'pearler',
  'peloton',
  'pennytel mobile',
  'peoplecare',
  'pepper leaf',
  'perifit',
  'pet chemist',
  'pet circle',
  'petculture',
  'petzyo',
  'phoenix health fund',
  'photobookshop',
  'picodi australia',
  'piping rock',
  'planet express',
  'plarium - plarium',
  'plenti (previously ratesetter)',
  'plico',
  'pluralsight',
  'pocketsmith',
  'pokémon go',
  'pokitpal',
  'polymail',
  'popcar',
  'popcultcha',
  'portal from facebook',
  'postando',
  'powerpal',
  'powershop',
  'premiumize',
  'presearch',
  'private internet access',
  'probikekit',
  'prohashing',
  'protonmail',
  'proud mary coffee',
  'pure-product',
  'purevpn',
  'qantas insurance - health insurance',
  'qantas insurance - qantas wellbeing app',
  'quad lock australia',
  'quandoo',
  'quantfury',
  'quidco',
  'quietgrowth',
  'quiksilver',
  'quizlet',
  'qv',
  'qwertee',
  'raiz',
  'rakuten',
  'rapha',
  'readwise',
  'rebtel',
  'receiptjar',
  'recollect',
  'recyclesmart',
  'red energy',
  'redbubble',
  'redteago',
  'refresh valet',
  'remarkable',
  'remitly',
  'renogy',
  'rentbetter',
  'reship.com',
  'revolut',
  'revolution beauty',
  'rewardsbunny',
  'ride',
  'ride on! entertainment',
  'riff raff & co',
  'ritual',
  'roberts space industries',
  'roboform',
  'rocketmiles',
  'rollie nation',
  "rollin' insurance (previously poncho insurance)",
  'runescape',
  'running heroes',
  'rush gold',
  'ry (recreate yourself)',
  'rydo',
  'safewill',
  'san churro',
  'sans drinks',
  'saxo markets',
  'sayso',
  'scentgod',
  'scratch pet food',
  'scribd',
  'secret lab chairs',
  'selfwealth',
  'setapp',
  'shady rays',
  'share with oscar',
  'sharesies',
  'sharesight',
  'shein',
  'shenzen audio',
  'shopback au',
  'shping',
  'simsdirect',
  'singx',
  'skillshare',
  'skrill',
  'skrill - btc crypto',
  'sleeping duck',
  'smart traveller',
  'smile',
  'snap send solve',
  'sniip',
  'socialgood',
  'society6',
  'sodastream',
  'solbari',
  'soulara',
  'sovol3d',
  'sparrow and fox',
  'spintel',
  'sportitude',
  'spriggy',
  'square',
  'square enix - final fantasy 14',
  'stackry',
  'stacksocial',
  'stake',
  'sticker mule',
  'stockspot',
  'stonemen',
  'stratia',
  'student universe us',
  'sugarsync',
  'sukin',
  'sumo',
  'sunglass hut',
  'super obvious',
  'super-rewards',
  'superfeast',
  'superhero',
  'superloop',
  'surfshark vpn',
  'surfstitch',
  'surveyz',
  'sweat coin',
  'swingvision',
  'swoop broadband',
  'swyftx crypto exchange',
  'syfe',
  'sync',
  't bar tea',
  'taco bell',
  'tamburlaine organic wines',
  'tangerine telecom',
  'tanggram',
  'taxibox',
  'teamm8',
  'ted baker',
  'temple & webster',
  'temu',
  'tennis gear',
  'tesla',
  'teslafi',
  'teslascope',
  'tessie',
  'the dinner ladies',
  'the iconic',
  'the oodie',
  'the perfect underwear',
  'the shade',
  'the sippery',
  'the whisky club',
  'the wine collective',
  'thefork',
  'thinx',
  'thr1ve',
  'tidal',
  'tidy me',
  'tiger brokers',
  'tile',
  'tipple',
  'todoist',
  'topcashback au',
  'topcashback uk',
  'topcashback us',
  'total tools',
  'tour radar',
  'tradingview',
  'travala',
  'tripod coffee',
  'true protein',
  'truefire',
  'trustedhousesitters',
  'tyresales',
  'tyroola',
  'ubank',
  'uber - drivers only',
  'uber carshare (formerly car next door)',
  'uber eats',
  'ufodrive',
  'ugg australia',
  'unbrk',
  'unique muscle',
  'uniti wireless / uniti internet',
  'unstoppable domains',
  'unyoked',
  'up bank',
  'upstreet',
  'urban company',
  'urban plant growers',
  'vauld',
  'ventraip',
  'vetsupply',
  "vic's meat",
  'vincero watches',
  'vinomofo',
  'virgin money',
  'virgin voyages',
  'vistaprint',
  'vitable',
  'vmp',
  'voip.ms',
  'vpa australia',
  'vultr',
  'waggly club',
  'waxit car care',
  'webull',
  'well home loans',
  'wemoney',
  'westfund health insurance',
  'wework',
  'whitehat jr',
  'who gives a crap',
  'whoop',
  'wiggle australia',
  'wiggle uk',
  'wilson parking',
  'windscribe',
  'wirex',
  'wise',
  'wonderbly',
  'woolovers',
  'woolworths mobile',
  'workflowy',
  'world of learning',
  'world of warships',
  'worldfirst',
  'worldremit',
  'xendpay',
  'yak pay',
  'yesstyle.com',
  'yolla calling app',
  'yomojo',
  'you need a budget',
  'you plate it',
  'youfoodz',
  'youhodler',
  'youtube - youtubepremium',
  'zavvi au',
  'zavvi uk',
  'zeller',
  'zenmarket',
  'zero co',
  'zip pay',
  'zipmex',
  'zoho',
  'zorali',
  'zwift',
];

const options = services.map((service) => ({
  name: service,
  value: service,
}));

export const searchServices = (term?: string) => {
  const cleanedTerm = term?.trim().toLowerCase();

  return options
    .filter((service) =>
      cleanedTerm ? service.name.includes(cleanedTerm) : true
    )
    .slice(0, 25);
};
