// serivce data is scraped from
// https://www.ozbargain.com.au/user/83105/edit/referrals
export const services = [
  'chope.co - chope phuket',
  '1cover',
  '3commas',
  'abi interiors',
  'abra',
  'active truth',
  'activeskin',
  'adore beauty',
  'afterpay',
  'ahm health insurance',
  'airbike',
  'airbnb - airbnb host',
  'airtasker',
  'airtax',
  'airwallex',
  'aliexpress',
  'alternative brewing',
  'amaysim',
  'amber',
  'amber electric',
  'american express - business explorer card',
  'american express - david jones card',
  'american express - david jones platinum card',
  'american express - essential credit card',
  'american express - explorer credit card',
  'american express - gold credit card',
  'american express - platinum business card',
  'american express - platinum card',
  'american express - platinum edge credit card',
  'american express - qantas business rewards card',
  'american express - qantas discovery card',
  'american express - qantas premium card',
  'american express - qantas ultimate card',
  'american express - velocity escape card',
  'american express - velocity platinum card',
  'amino z',
  'ampol',
  'appsumo',
  'artscow - 1. new accounts',
  'artscow - 10 selected items',
  'artscow - cosmetic bag',
  'artscow - leggings',
  'artscow - mousepad',
  'artscow - name stamp',
  'artscow - phone case',
  'artscow - photo specialbook',
  'artscow - skater skirt',
  'artscow - tank top',
  'artscow - watch',
  'athena home loan',
  'athletic greens',
  'ausmed',
  'aussie broadband',
  'aussie house sitters',
  'azimo',
  'backblaze',
  'bada bean',
  'bamboo',
  'banggood',
  'beam',
  'beam wallet',
  'beeco',
  'beerco',
  'befrugal',
  'belong - belong (mobile)',
  'belong - belong broadband',
  "ben & jerry's inside scoop",
  "benny's boardroom",
  'bicycle nsw',
  'bill hero',
  'billy bubbles',
  'binance',
  'binary lane',
  'bitpanda',
  'bitstamp',
  'block earner',
  'blockfi',
  'blossom',
  'blys',
  'board game master',
  'bokksu',
  'boody',
  'boost your super',
  'boozebud',
  'border bank',
  'boxcryptor - boxcryptor unlimited',
  'brand house direct',
  'brazilian beauty',
  'brosa furniture',
  'bubble tea club',
  'bugaboo',
  'bulk powders',
  'bundll',
  'bunny.net',
  'butterfly network',
  'buyandship',
  'bybit',
  'byte australia',
  'cake defi',
  'caltex / star mart - caltex fuelpay',
  'canningvale',
  'canva',
  'car next door',
  'carbar',
  'cardly',
  'cashrewards',
  'castlery',
  'cat harness australia',
  'cell care',
  'cellar one',
  'cellardoor.co',
  'celsius network',
  'chatbooks',
  'chatime',
  'chefgood',
  'chefs on wheels',
  'chipolo',
  'circles.life',
  'classpass',
  'cmc markets',
  'code camp',
  'coinbase',
  'coinjar',
  'coinlist',
  'coinspot',
  'coinstash',
  'cointracker',
  'cointracking',
  'cointree crypto exchange',
  'comgateway',
  'comptia',
  'core powerfoods',
  'covau energy',
  'cowcow - $0.99 shoptell items',
  'cowcow - $3.99 shoptell items',
  'cowcow - $7.99 shoptell items',
  'cowcow - custom glasses cloths',
  'cowcow - custom handbag mirrors',
  'cowcow - name stamp',
  'creative labs',
  'crypto.com',
  'cubic technology',
  'cubo ai',
  'cult beauty',
  'cupshe',
  'currencyfair',
  'dash delivers',
  'dashlane',
  'datacamp',
  'dataquest',
  'decathlon australia',
  'degoo',
  'deliveroo',
  'dharma bums',
  'diamond energy',
  'didi - didi',
  'different drop',
  'digital ocean',
  'digital surge',
  'dinner twist',
  'distrokid',
  "doctors' health fund",
  'dollar shave club - fbuy.me links',
  'doordash',
  'doordash - drivers/dashers only',
  'driva',
  'drop',
  'dropbox',
  'duolingo',
  'dynadot',
  'dynalist',
  'e-living furniture',
  'e-pocket',
  'easi',
  'easyequities',
  'eatclub',
  'eco modern essentials',
  'econaps',
  'ecostainable',
  'educative',
  'elbaite',
  'elite supplements',
  'ellus & krue',
  'elysian energy',
  'emma sleep',
  'energy locals',
  'enphase',
  'esther & co.',
  'etax accountants',
  'ethique',
  'etoro',
  'ettitude',
  'eva mattress',
  'evee',
  'evernote',
  'everyplate',
  'evolve skateboards',
  'exetel',
  'expressvpn',
  'eyebuydirect',
  'ezlicence',
  'fanatical',
  'fantastic services',
  'fantuan',
  'fastcover',
  'fastmail',
  'felix mobile',
  'filefactory',
  'finder - finder wallet (app)',
  'fishme',
  'fite',
  'fitness first',
  'fitness outcomes',
  'fitstop',
  'five senses coffee',
  'flexicar',
  'flexiroam',
  'flip tv',
  'floraly',
  'found concrete',
  'freelancer',
  'french sweet',
  'from japan',
  'ftx',
  'funding',
  'furthr',
  'future broadband',
  'fuzenet internet',
  'gameology',
  'garden of vegan',
  'gate.io',
  'gdgt deals (engadget stacksocial)',
  'gelid store',
  'gem',
  'gemini exchange',
  'get2020 optometry',
  'giffgaff',
  'gimme',
  'giving assistant',
  'glamcorner',
  'globird energy',
  'gocashback',
  'gocatch',
  'goget carshare',
  'goldfields toys & games',
  'good pair days',
  'goodments',
  'goodnessme',
  'google workspace',
  'gozney',
  'groupee',
  'groupon uk',
  'guzman y gomez',
  'gwent',
  'hay',
  'hello drinks',
  'hellofresh',
  'heritage bank - $100 referral + win $1000 with new account',
  'heritage bank - $250 gift card with loan',
  'hey antonella',
  'hey bianca',
  'hey you',
  'hif',
  'hillview farms',
  'hipcamp',
  'hnry',
  'hodlnaut',
  'homeseer',
  'honey',
  'hotel tonight',
  'hp smart',
  'hqhair',
  'humaniti',
  'humble bundle - humble choice',
  'hummingbird',
  'icebreaker',
  'ig group',
  'iherb.com',
  'independent reserve',
  'ing',
  'ingogo',
  'instacoin',
  'instarem',
  'institchu',
  'integrately',
  'interactive brokers australia',
  'ipantry',
  'iri shopper panel',
  'italki',
  'ivacy vpn',
  'iwoot',
  "jim's home fresh deliveries",
  'jimmy brings',
  'joonya eco wipes',
  'just wines',
  "kennards self storage - kennard's self storage",
  'ker-ching!',
  'keychron',
  'keysmart',
  'kickback australia',
  "kiehl's",
  'kiwico',
  'klarna',
  'klook',
  'knobby',
  'knockaround',
  'koala',
  'kobo',
  'kogan',
  'koinly',
  'kriptomat',
  'krisp',
  'kucoin',
  'launtel',
  'ledn',
  'lila beauty',
  'lime',
  'lingoda',
  'linode',
  'liven',
  'loans.com.au',
  'lookfantastic au',
  'lookfantastic uk',
  "looma's",
  'loungebuddy',
  'loyalty app',
  'lskd',
  'lumo energy',
  'lunch money',
  'luno',
  'lupe technology',
  'luxury escapes',
  'macro mike',
  'macros',
  'marriott',
  'mashable',
  'mate communicate',
  'max brenner',
  'me bank',
  'mealpal',
  'medibank private',
  'mee audio',
  'memberbuy',
  'mexc global',
  'milkrun',
  'mingle seasoning',
  'missguided australia',
  'mixbook',
  'mobvoi',
  'mocka',
  'modibodi',
  'mojo power',
  'momentum energy',
  'moneygram',
  'monta',
  'moo',
  'moogoo',
  'moomoo',
  'morpher',
  'mr. rebates',
  'mubi',
  'my foodie box',
  'my muscle chef',
  'mypaynow',
  'myprotein',
  'myrepublic',
  'myus.com',
  'naked wines',
  'naritas finance',
  'native deodorant',
  'natural cycles',
  'natvia',
  'navexa',
  'nectr',
  'neowin',
  'neuron mobility',
  'news demon',
  'nexo',
  'nielsen - beauty panel',
  'nielsen - broadband panel',
  'nielsen - homescan',
  'nightowl convenience',
  'noa home',
  'nodeone',
  'nonda',
  'nordvpn',
  'normcore coffee',
  'nourished life',
  'novelship',
  'numobile',
  'nuraphone',
  'nutrition xpress',
  'nuts about life',
  'oculus',
  'okcoin',
  'okex',
  'ola australia',
  'olive young',
  'one.com - warp',
  'onedrive',
  'onmarket bookbuilds',
  'openphone',
  'oporto',
  'orbitkey',
  'orbitremit',
  'origin energy - origin',
  'origin energy - origin spike',
  'otaku mode',
  'our cow',
  'oura',
  'ovo energy',
  'ozsale',
  'ozsale mobile',
  'parabo press',
  'park on king',
  'parkhound',
  'patpat',
  'payo',
  'paysend',
  'pd car insurance',
  'pearler',
  'peloton',
  'pennytel mobile',
  'peoplecare',
  'pepper leaf',
  'perifit',
  'pet circle',
  'petculture',
  'petpost',
  'petzyo!',
  'phoenix health fund',
  'photobookshop',
  'piping rock',
  'placie',
  'planet express',
  'plarium - plarium',
  'plenti (previously ratesetter)',
  'pluralsight',
  'pocketsmith',
  'pokã©mon go',
  'pokitpal',
  'polymail',
  'popcar',
  'portal from facebook',
  'powerpal',
  'powershop',
  'premiumize',
  'presearch',
  'private internet access',
  'probikekit',
  'prohashing',
  'protonmail',
  'qantas insurance - app download',
  'qantas insurance - health insurance',
  'qenergy',
  'qiqqa',
  'quad lock australia',
  'quandoo',
  'quantfury',
  'quidco',
  'quietgrowth',
  'quiksilver',
  'quizlet',
  'qwertee',
  'raiz',
  'rakuten',
  'readwise',
  'reamped energy',
  'rebtel',
  'receiptjar',
  'red energy',
  'redbubble',
  'refresh valet',
  'remarkable',
  'remitly',
  'renogy',
  'rentbetter',
  'reship.com',
  'rev',
  'revolut',
  'revolution beauty',
  'rewardsbunny',
  'ride',
  'ride on! entertainment',
  'riff raff & co',
  'ritual',
  'road id',
  'roberts space industries',
  'roboform',
  'rocketmiles',
  'rollie nation',
  "rollin' insurance (previously poncho insurance)",
  'runescape',
  'running heroes',
  'rush gold',
  'ry (recreate yourself)',
  'rydo',
  'safewill',
  'samsung',
  'saxo markets',
  'sayso',
  'science in sport',
  'scratch pet food',
  'scribd',
  'secret lab chairs',
  'selfwealth',
  'shady rays',
  'share with oscar',
  'sharesight',
  'shein',
  'shenzen audio',
  'shopback au',
  'shping',
  'skillshare',
  'skrill',
  'skrill - btc crypto',
  'sleep cycle',
  'sleeping duck',
  'smile',
  'smile direct club',
  'snap send solve',
  'sniip',
  'socialgood',
  'society6',
  'soulara',
  'spaceship',
  'sportitude',
  'sports power geelong',
  'spriggy',
  'square',
  'stablehouse',
  'stackry',
  'stacksocial',
  'stake',
  'sticker mule',
  'stockspot',
  'stonemen',
  'student universe',
  'sugarsync',
  'sukin',
  'sumo',
  'super-rewards',
  'superfeast',
  'superhero',
  'superloop',
  'surfshark vpn',
  'surfstitch',
  'surveyz',
  'swingvision',
  'swyftx crypto exchange',
  'sync',
  'taco bell',
  'tamburlaine organic wines',
  'tangerine telecom',
  'tanggram',
  'tap air portugal',
  'taxibox',
  'ted baker',
  'temple & webster',
  'teslafi',
  'teslascope',
  'the dinner ladies',
  'the dirt company',
  'the iconic',
  'the oodie',
  'the perfect underwear',
  'the sippery',
  'the whisky club',
  'the wine collective',
  'thefork',
  'thinx',
  'thr1ve',
  'tidal',
  'tidy me',
  'tiger brokers',
  'tiktok',
  'tile',
  'tipple',
  'todoist',
  'topcashback uk',
  'topcashback us',
  'total tools',
  'tour radar',
  'tradingview',
  'travala',
  'tripod coffee',
  'true protein',
  'tyresales',
  'tyroola',
  'ubank',
  'uber - drivers only',
  'uber eats',
  'ufodrive',
  'ugg australia',
  'unbrk',
  'unique muscle',
  'uniti wireless',
  'unstoppable domains',
  'up bank',
  'upstreet',
  'vantage fx',
  'vauld',
  'ventraip',
  'vet supply',
  "vic's meat",
  'vincero watches',
  'vinomofo',
  'virgin money',
  'vistaprint',
  'vitable',
  'voip.ms',
  'voly',
  'vpa australia',
  'vultr',
  'well home loans',
  'wemoney',
  'westfund health insurance',
  'who gives a crap',
  'whoop',
  'wiggle australia',
  'wiggle uk',
  'wilson parking',
  'windscribe',
  'wirex',
  'wise',
  'woolovers',
  'woolworths mobile',
  'workflowy',
  'world of learning',
  'worldfirst',
  'worldremit',
  'xendpay',
  'yesstyle.com',
  'yomojo',
  'you need a budget',
  'you plate it',
  'youfoodz',
  'youhodler',
  'yourgrocer.com.au',
  'zavvi au',
  'zavvi uk',
  'zenmarket',
  'zenni optical',
  'zero co',
  'zip.co',
  'zipmex',
  'zoho',
];

const options = services.map((service) => ({ name: service, value: service }));

export const searchServices = (term?: string) => {
  const cleanedTerm = term?.trim().toLowerCase();

  return options
    .filter((service) =>
      cleanedTerm ? service.name.includes(cleanedTerm) : true
    )
    .slice(0, 25);
};
