// service data is scraped from https://www.ozbargain.com.au/user/83105/edit/referrals
const OZBARGAIN_SERVICES: string[] = [
  '1st energy',
  '3commas',
  'abra',
  'accor plus',
  'active truth',
  'admirals',
  'adore beauty',
  'aeg power tools',
  'afterpay',
  'ahm health insurance',
  'airalo',
  'airbike',
  'airbnb - airbnb host',
  'airtax',
  'airvpn',
  'airwallex',
  'aliexpress',
  'alpha-h',
  'alternative brewing',
  'amaysim',
  'amazingco',
  'amber',
  'amber electric',
  'american express - essential credit card',
  'american express - platinum card',
  'american express - platinum edge credit card',
  'american express - qantas discovery card',
  'american express - qantas ultimate card',
  'american express - qantas premium card',
  'american express - velocity platinum card',
  'american express - velocity escape card',
  'american express - explorer credit card',
  'american express - qantas business rewards card',
  'american express - business explorer card',
  'american express - velocity business card',
  'american express - centurion personal charge card',
  'amino z',
  'ampol',
  'anz',
  'appliances online',
  'appsumo',
  'artscow - 1. new accounts',
  'artscow - name stamp',
  'asian pantry',
  'asos',
  'athena home loan',
  'athletic greens',
  'aussie broadband',
  'aussie house sitters',
  'aussie pharma direct',
  'australian unity',
  'autoguru',
  'awardwallet',
  'backblaze',
  'bamboo',
  'banggood',
  'bano',
  'baopals',
  'barbell foods',
  'beach burrito',
  'beam',
  'beam wallet',
  'beerhug',
  'befrugal',
  'belong - belong (mobile)',
  'belong - belong broadband',
  "ben & jerry's inside scoop",
  'better world books',
  'bill hero',
  'billy bubbles',
  'binance - standard',
  'binance - lite - usdt',
  'binary lane',
  'bird',
  'bitcoin.com.au',
  'bitpanda',
  'bitrefill',
  'bitstamp',
  'bizcover',
  'black type x',
  'blackship',
  'block earner',
  'blossom',
  'bluetti australia',
  'blys',
  'board game master',
  'bokksu',
  'bondi sands',
  'boody bamboo clothing',
  'boost your super',
  'border bank',
  'bose australia',
  'boxcryptor - boxcryptor unlimited',
  'brand house direct',
  'brazilian beauty',
  'brookfarm',
  'brooks running',
  'bubble tea club',
  'bulk nutrients',
  'bunny.net',
  'bupa',
  'burgertory',
  'butterfly network',
  'buyandship',
  'bybit',
  'byte australia',
  'cake defi',
  'caltex / star mart - caltex fuelpay',
  'canningvale',
  'canva',
  'cardly',
  'cariuma',
  'cashrewards',
  'castlery',
  'cell care',
  'cellar one',
  'cellardoor.co',
  "chargrill charlie's",
  'chatbooks',
  'chatime',
  'cheeky plant co.',
  'chefgood',
  'chefs on wheels',
  'chief nutrition',
  'chipolo',
  'chope - chope phuket',
  'circles.life',
  'classpass',
  'code camp',
  'coinjar',
  'coinlist',
  'coinspot',
  'coinstash',
  'cointracker',
  'cointracking',
  'cointree crypto exchange',
  'comgateway',
  'coolkidz australia',
  'core powerfoods',
  'coupert',
  'covau energy',
  'cowcow - name stamp',
  'cowcow - custom handbag mirrors',
  'cowcow - custom glasses cloths',
  'cowcow - $3.99 shoptell items',
  'cowcow - $7.99 shoptell items',
  'creative labs',
  'crypto.com',
  'cryptospend',
  'cubo ai',
  'cult beauty',
  'cupshe',
  'currencyfair',
  "daniel's donuts",
  'dashlane',
  'dataquest',
  'decathlon australia',
  'degoo',
  'dental 99',
  'dharma bums',
  'di pacci coffee company',
  'diamond energy',
  'didi - didi',
  'digital ocean',
  'dinner twist',
  'dinnerly',
  'distrokid',
  "doctors' health fund",
  'dollar shave club - fbuy.me links',
  'doordash',
  'doordash - drivers/dashers only',
  'douugh',
  'dozen deals',
  'dr. dough',
  'dresden vision',
  'drinkmate australia',
  'drop',
  'dropbox',
  'duolingo',
  'dynadot',
  'e-living furniture',
  'e-pocket',
  'easyequities',
  'eatclub',
  'eco. modern essentials',
  'econaps',
  'elbaite',
  'elite supplements',
  'ellus & krue',
  'emma sleep',
  'energy locals',
  'enphase',
  'eskimo',
  'esr gear',
  'etax accountants',
  'ethique',
  'etoro',
  'etsy - seller',
  'ettitude',
  'eubi australia',
  'euca (proud products)',
  'eva mattress',
  'evee',
  'everyday mobile from woolworths',
  'everyplate',
  'evolve skateboards',
  'exetel',
  'expressvpn',
  'eyebuydirect',
  'ezlicence',
  'fancraze',
  'fantastic services',
  'fantuan',
  'fastcover',
  'fastmail',
  'felix mobile',
  'fever',
  'fig & blooms',
  'first table australia',
  'fishme',
  'fite',
  'fitstop',
  'fiverr',
  'flexicar',
  'flexiroam',
  'flip tv',
  'foody bag',
  'framefox',
  'freelancer',
  'freeletics',
  'french sweet',
  'from japan',
  'funding',
  'furthr',
  'future broadband',
  'futuregolf',
  'fuzenet internet',
  'gameology',
  'gami chicken & beer',
  'garden of vegan',
  'gate.io',
  'gdgt deals (engadget stacksocial)',
  'gemini exchange',
  'giffgaff',
  'gimme',
  'glamcorner',
  'globird energy',
  'gocardless',
  'gocashback',
  'gocatch',
  'goldfields toys & games',
  'good pair days',
  'goodments',
  'goodnessme',
  'google workspace',
  'gozney',
  'groupon uk',
  'guzman y gomez',
  'gwent',
  'gym and fitness',
  'h&m',
  'hay',
  'hellofresh - $115-$125 off 1st box',
  'her black book',
  'heritage bank - $250 gift card with loan',
  'hey bianca',
  'heymax',
  'hif',
  'hillview farms',
  'hipcamp',
  'hnry',
  'hodlnaut',
  'homeseer',
  'honey',
  'honey insurance',
  'hopper',
  'hotel tonight',
  'hp instant ink',
  'hqhair',
  'humble bundle - humble choice',
  'hummingbird',
  'hyper karting',
  'icebreaker',
  'ifttt',
  'ig group',
  'iherb.com',
  'independent reserve',
  'infinicloud',
  'ing',
  'ingogo',
  'instantscripts',
  'instarem',
  'institchu',
  'integrately',
  'interactive brokers australia',
  'ipantry',
  'iri shopper panel',
  'italki',
  'ivacy vpn',
  'iwallpaper / macos game studio - iwallpaper',
  'iwoot',
  'jamie kay',
  'jimmy brings',
  'joonya eco wipes',
  'juniper',
  'just esim hong kong',
  'just wines',
  'kegland',
  "kennards self storage - kennard's self storage",
  'kent street cellars',
  'ker-ching!',
  'kickback australia',
  "kiehl's",
  'kitsch',
  'kiwico',
  'klarna',
  'klook travel',
  'knobby',
  'koala',
  'kobo',
  'kogan',
  'koh',
  'koinly',
  'koogle',
  'krisp',
  'kucoin',
  'kx pilates',
  'lalal.ai',
  'launtel',
  'leaptel',
  'ledger',
  'ledn',
  'life cykel',
  'lila beauty',
  'lime',
  'lingoda',
  'linode',
  'loaded lifting',
  'loans.com.au',
  'localcart',
  'lookfantastic au',
  'lookfantastic uk',
  "looma's",
  'loop earplugs',
  'loyalty app',
  'lskd',
  'lucy & yak',
  'lumin',
  'lumo energy',
  'luno',
  'luxury escapes',
  'lyka',
  'mac cosmetics',
  'macros',
  'mad paws',
  'madura tea',
  'marley spoon',
  'marriott',
  'mashable',
  'mask co',
  'mate communicate',
  'me bank',
  'mealpal',
  'medibank private',
  'mee audio',
  'memberbuy',
  'menulog - drivers/couriers',
  'meta store',
  'mexc global',
  'minisforum',
  'missguided australia',
  'mixbook',
  'mobvoi',
  'modibodi',
  'mofo smile',
  'mojo power',
  'momentum energy',
  'moneygram',
  'monta',
  'moo',
  'moogoo',
  'moomoo',
  'mr. rebates',
  'mubi',
  'muscle diets',
  'muscle nation',
  'my foodie box',
  'my muscle chef',
  'mypaynow',
  'myprotein',
  'myus.com',
  'naked wines',
  'nanoblock',
  'naritas finance',
  'natvia',
  'navexa',
  'nba top shot',
  'nectr',
  'neowin',
  'neuron mobility',
  'news demon',
  'nexo',
  'nextpair',
  'nielsen - homescan',
  'nightowl convenience',
  'no pong',
  'noa home',
  'nodeone',
  'nomador',
  'nonda',
  'nordpass',
  'nordvpn',
  'normcore coffee',
  'nourished life',
  'novelship',
  'numobile',
  'nuraphone',
  'oakley',
  'okcoin',
  'okx',
  'olive young',
  'one month',
  'one.com - warp',
  'onedrive',
  'onepass',
  'onmarket bookbuilds',
  'orange poland',
  'orbitremit',
  'origin energy - origin spike',
  'ororo',
  'otaku mode',
  'oura',
  'outschool',
  'ovo energy',
  'oz hair & beauty',
  'ozsale',
  'ozsale mobile',
  'panda remit',
  'park on king',
  'parkhound',
  'patpat',
  'pay.com.au',
  'payo',
  'paysend',
  'pd car insurance',
  'pearler',
  'peloton',
  'pennytel mobile',
  'peoplecare',
  'pepper leaf',
  'perifit',
  'pet chemist',
  'pet circle',
  'petzyo',
  'phoenix health fund',
  'photobookshop',
  'picodi australia',
  'pingme',
  'piping rock',
  'planet express',
  'plenti (previously ratesetter)',
  'plico',
  'pluralsight',
  'pocketsmith',
  'pod & parcel',
  'pokémon go',
  'pokitpal',
  'polestar',
  'polymail',
  'popcar',
  'popcultcha',
  'powerpal',
  'powershop',
  'presearch',
  'private internet access',
  'probikekit',
  'prohashing',
  'protonmail',
  'proud mary coffee',
  'pure-product',
  'purevpn',
  'qantas insurance - health insurance',
  'qantas insurance - qantas wellbeing app',
  'quad lock australia',
  'quandoo',
  'quantfury',
  'quidco',
  'quietgrowth',
  'quiksilver',
  'quizlet',
  'qv',
  'qwertee',
  'raiz',
  'rakuten',
  'rapha',
  'readwise',
  'rebtel',
  'receiptjar',
  'recollect',
  'recyclesmart',
  'red bull mobile',
  'red energy',
  'redbubble',
  'redteago',
  'refresh valet',
  'remarkable',
  'remitly',
  'renogy',
  'rentbetter',
  'reship.com',
  'revolut',
  'revolution beauty',
  'rewardsbunny',
  'ride on! entertainment',
  'ritual',
  'roamless',
  'roberts space industries',
  'roboform',
  'robot my life',
  'rocketmiles',
  'rollie nation',
  "rollin' insurance (previously poncho insurance)",
  'runescape',
  'rush gold',
  'ry (recreate yourself)',
  'safewill',
  'san churro',
  'sans drinks',
  'saxo markets',
  'sayso',
  'scratch pet food',
  'scribd',
  'secret lab chairs',
  'selfwealth',
  'setapp',
  'shady rays',
  'share with oscar',
  'sharesies',
  'sharesight',
  'shein',
  'shenzen audio',
  'shopback au',
  'shping',
  'sigmaos',
  'simsdirect',
  'singapore airlines',
  'singx',
  'skillshare',
  'skrill',
  'skrill - btc crypto',
  'sleeping duck',
  'smart traveller',
  'smile',
  'snap send solve',
  'sniip',
  'socialgood',
  'society6',
  'sodastream',
  'solaredge',
  'solbari',
  'soulara',
  'sovol3d',
  'spaceship',
  'sparrow and fox',
  'speechify',
  'spintel',
  'sportitude',
  'spriggy',
  'square',
  'square enix - final fantasy 14',
  'stackry',
  'stacksocial',
  'stake',
  'sticker mule',
  'stockspot',
  'stonemen',
  'stratia',
  'student universe us',
  'sugarsync',
  'sukin',
  'sumo',
  'sunglass hut',
  'super obvious',
  'super-rewards',
  'superfeast',
  'superhero',
  'superloop',
  'surfshark vpn',
  'surfstitch',
  'surveyz',
  'swagbucks',
  'sweat coin',
  'swingvision',
  'swoop broadband',
  'swyftx crypto exchange',
  'syfe',
  'sync',
  't bar tea',
  'taco bell',
  'tamburlaine organic wines',
  'tangerine telecom',
  'tanggram',
  'taxibox',
  'teamm8',
  'ted baker',
  'tel-u',
  'tempdrop',
  'temple & webster',
  'temu',
  'tennis gear',
  'tesla',
  'teslafi',
  'teslascope',
  'tessie',
  'the dinner ladies',
  'the garden superstore',
  'the iconic',
  'the memo',
  'the oodie',
  'the pass loyalty app',
  'the perfect underwear',
  'the shade',
  'the sippery',
  'the whisky club',
  'the whisky list',
  'the wine collective',
  'thefork',
  'thinx',
  'tidy me',
  'tiger brokers',
  'tile',
  'tipple',
  'tirtyl',
  'todoist',
  'topcashback au',
  'topcashback uk',
  'topcashback us',
  'total tools',
  'tour radar',
  'tradingview',
  'travala',
  'tripod coffee',
  'true protein',
  'truefire',
  'trustedhousesitters',
  'tyresales',
  'tyroola',
  'ubank',
  'uber - drivers only',
  'uber carshare (formerly car next door)',
  'uber eats',
  'ubigi',
  'ufodrive',
  'ugg australia',
  'ultra violette',
  'unbrk',
  'unique muscle',
  'uniti wireless / uniti internet',
  'unstoppable domains',
  'unyoked',
  'up bank',
  'updoc',
  'upstreet',
  'urban company',
  'urban plant growers',
  'vauld',
  'ventraip',
  'vetsupply',
  'viator',
  "vic's meat",
  'vincero watches',
  'vinomofo',
  'virgin active',
  'virgin money',
  'virgin voyages',
  'virgo',
  'vistaprint',
  'vitable',
  'vmp',
  'voip.ms',
  'vpa australia',
  'vultr',
  'waggly club',
  'waxit car care',
  'we might be tiny',
  'webull',
  'well home loans',
  'wemoney',
  'westfund health insurance',
  'wework',
  'whitehat jr',
  'who gives a crap',
  'whoop',
  'wiggle australia',
  'wiggle uk',
  'wilson parking',
  'windscribe',
  'wirex',
  'wise',
  'wonderbly',
  'woolovers',
  'workflowy',
  'world of learning',
  'world of warships',
  'worldfirst',
  'worldremit',
  'xe',
  'xendpay',
  'yak pay',
  'yesstyle.com',
  'yolla calling app',
  'yomojo',
  'you need a budget',
  'you plate it',
  'youfoodz',
  'youhodler',
  'zavvi au',
  'zavvi uk',
  'zeller',
  'zenmarket',
  'zero co',
  'zip pay',
  'zipmex',
  'zoho',
  'zorali',
  'zwift',
];

const CUSTOM_SERVICES: string[] = ['everyday extra (woolworths & big w)'];

export const services: string[] = [...new Set([...OZBARGAIN_SERVICES, ...CUSTOM_SERVICES])];

const options = services.map((service) => ({
  name: service,
  value: service,
}));

export const searchServices = (term: string) => {
  const cleanedTerm = term?.trim().toLowerCase();

  return options.filter((service) => (cleanedTerm ? service.name.includes(cleanedTerm) : true)).slice(0, 25);
};
