services:
  # Main App Database
  db:
    image: postgres:17-alpine
    restart: on-failure
    env_file: ".env"
    container_name: discord_bot_db
    ports:
      - 5432:5432
    volumes:
      - ./.docker/volume/db/data:/var/lib/postgresql/data

  # OpenTelemetry Backend (OpenObserve)
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: vait_openobserve
    ports:
      - "5080:5080"   # HTTP UI + OTLP HTTP
      - "5081:5081"   # gRPC
    volumes:
      - ./.docker/volume/openobserve-data:/data
    environment:
      - ZO_ROOT_USER_EMAIL=root@example.com
      - ZO_ROOT_USER_PASSWORD=Complexpass#123
      - ZO_DATA_DIR=/data
