name: setup-node-dependencies
description: Setup Node Dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ^8.15.0

    - name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Set up project
      shell: bash
      run: pnpm install

    - name: Generate Prisma types
      shell: bash
      run: pnpm prisma:gen
