name: Build OzBargain referrals list

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *'
  push:
    branches:
      - test-referrals-automate

jobs:
  build-referrals-list:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up project
        uses: ./.github/actions/setup-node-deps

      - name: Build OzBargain referrals list
        run: pnpm run build:referrals
        env:
          AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
          AXIOM_DATASET: ${{ secrets.AXIOM_DATASET }}
          AXIOM_ORG_ID: ${{ secrets.AXIOM_ORG_ID }}
          CLIENT_ID: blank
          TOKEN: blank
          DATABASE_URL: blank

      - name: print out file
        run: |
          ls src/commands/referral/generated
          cat src/commands/referral/generated/ozbargain-services.json

      - name: Setup Git Credentials
        run: |
          git config --global user.email "admin@vietausit.com"
          git config --global user.name "Vietausit Admin (Github Actions)"
          git status --porcelain

      - name: Compare changes and create PR if succeed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ `git status --porcelain` ]]; then
            git checkout -b automated-referrals-update
            git add src/commands/referral
            git commit -m "chore: update ozbargain referrals list"
            git push -u origin automated-referrals-update
            gh pr create --fill --base master
          else
            echo "No changes to report"
          fi
